# Generated by Django 5.2.4 on 2025-10-08 20:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='رمز المادة')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('description', models.TextField(blank=True, verbose_name='وصف المادة')),
                ('credit_hours', models.IntegerField(verbose_name='الساعات المعتمدة')),
                ('level', models.CharField(choices=[('1', 'المستوى الأول'), ('2', 'المستوى الثاني'), ('3', 'المستوى الثالث'), ('4', 'المستوى الرابع'), ('5', 'المستوى الخامس'), ('6', 'المستوى السادس')], max_length=1, verbose_name='المستوى')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الطالب')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('level', models.CharField(choices=[('1', 'المستوى الأول'), ('2', 'المستوى الثاني'), ('3', 'المستوى الثالث'), ('4', 'المستوى الرابع'), ('5', 'المستوى الخامس'), ('6', 'المستوى السادس')], max_length=1, verbose_name='المستوى')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='صورة الطالب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الدرجة')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course', verbose_name='المادة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسجيل',
                'verbose_name_plural': 'التسجيلات',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
