# Generated by Django 5.2.16 on 2026-07-12 15:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='العام الدراسي')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_current', models.BooleanField(default=False, verbose_name='العام الحالي')),
            ],
            options={
                'verbose_name': 'عام دراسي',
                'verbose_name_plural': 'الأعوام الدراسية',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='اسم البند المالي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ الافتراضي')),
            ],
            options={
                'verbose_name': 'بند مالي',
                'verbose_name_plural': 'البنود المالية',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم ولي الأمر')),
                ('national_id', models.CharField(blank=True, max_length=30, verbose_name='رقم الهوية')),
                ('relationship', models.CharField(choices=[('father', 'الأب'), ('mother', 'الأم'), ('brother', 'الأخ'), ('sister', 'الأخت'), ('other', 'قريب آخر')], default='father', max_length=10, verbose_name='صلة القرابة')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('alternate_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم إضافي')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('occupation', models.CharField(blank=True, max_length=120, verbose_name='الوظيفة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'ولي أمر',
                'verbose_name_plural': 'أولياء الأمور',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المدرسة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود المدرسة')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/', verbose_name='شعار المدرسة')),
                ('is_active', models.BooleanField(default=True, verbose_name='حالة المدرسة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مدرسة',
                'verbose_name_plural': 'المدارس',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'تسجيل مادة', 'verbose_name_plural': 'تسجيلات المواد'},
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('core', 'أساسية'), ('lab', 'عملي'), ('activity', 'نشاط'), ('elective', 'اختيارية')], default='core', max_length=10, verbose_name='نوع المادة'),
        ),
        migrations.AddField(
            model_name='course',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='الدرجة النهائية'),
        ),
        migrations.AddField(
            model_name='course',
            name='pass_mark',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درجة النجاح'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الحضور'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ القبول'),
        ),
        migrations.AddField(
            model_name='student',
            name='national_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='رقم الهوية'),
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقوف'), ('graduated', 'متخرج'), ('withdrawn', 'منسحب')], default='active', max_length=12, verbose_name='الحالة الدراسية'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, verbose_name='رمز المادة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.IntegerField(default=1, verbose_name='عدد الحصص'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('1', 'الصف 1'), ('2', 'الصف 2'), ('3', 'الصف 3'), ('4', 'الصف 4'), ('5', 'الصف 5'), ('6', 'الصف 6'), ('7', 'الصف 7'), ('8', 'الصف 8'), ('9', 'الصف 9'), ('10', 'الصف 10'), ('11', 'الصف 11'), ('12', 'الصف 12')], max_length=2, verbose_name='الصف'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='myapp.course', verbose_name='المادة'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة النهائية'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='myapp.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('1', 'الصف 1'), ('2', 'الصف 2'), ('3', 'الصف 3'), ('4', 'الصف 4'), ('5', 'الصف 5'), ('6', 'الصف 6'), ('7', 'الصف 7'), ('8', 'الصف 8'), ('9', 'الصف 9'), ('10', 'الصف 10'), ('11', 'الصف 11'), ('12', 'الصف 12')], max_length=2, verbose_name='الصف'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='رقم الطالب'),
        ),
        migrations.AddField(
            model_name='course',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='myapp.academicyear', verbose_name='العام الدراسي'),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='myapp.academicyear', verbose_name='العام الدراسي'),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='اسم الاختبار')),
                ('assessment_type', models.CharField(choices=[('quiz', 'اختبار قصير'), ('exam', 'اختبار'), ('assignment', 'واجب'), ('project', 'مشروع')], max_length=20, verbose_name='نوع الاختبار')),
                ('term', models.CharField(choices=[('term1', 'الفصل الأول'), ('term2', 'الفصل الثاني'), ('final', 'نهائي')], max_length=10, verbose_name='الفصل')),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='الدرجة العظمى')),
                ('due_date', models.DateField(verbose_name='تاريخ الاختبار')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='myapp.course', verbose_name='المادة')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='myapp.guardian', verbose_name='ولي الأمر'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='رقم الفاتورة')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان الفاتورة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصم')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'مستحقة'), ('partial', 'مدفوعة جزئيًا'), ('paid', 'مدفوعة'), ('overdue', 'متأخرة')], default='pending', max_length=10, verbose_name='حالة الفاتورة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='myapp.academicyear', verbose_name='العام الدراسي')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='myapp.feecategory', verbose_name='البند المالي')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='myapp.student', verbose_name='الطالب')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='المبلغ المدفوع')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الدفع')),
                ('method', models.CharField(choices=[('cash', 'نقدي'), ('transfer', 'تحويل'), ('card', 'بطاقة')], max_length=10, verbose_name='طريقة الدفع')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='رقم المرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='myapp.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
            },
        ),
        migrations.AddField(
            model_name='guardian',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.school', verbose_name='المدرسة'),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.school', verbose_name='المدرسة'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.school', verbose_name='المدرسة'),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.school', verbose_name='المدرسة'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.school', verbose_name='المدرسة'),
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='اسم الصف/الشعبة')),
                ('stage', models.CharField(choices=[('primary', 'ابتدائي'), ('middle', 'إعدادي'), ('secondary', 'ثانوي')], max_length=10, verbose_name='المرحلة')),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='رقم الصف')),
                ('section', models.CharField(blank=True, max_length=20, verbose_name='الشعبة')),
                ('room_number', models.CharField(blank=True, max_length=20, verbose_name='رقم القاعة')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='السعة')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='myapp.academicyear', verbose_name='العام الدراسي')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'صف دراسي',
                'verbose_name_plural': 'الصفوف الدراسية',
                'ordering': ['level', 'section'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='myapp.schoolclass', verbose_name='الصف الدراسي'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='myapp.schoolclass', verbose_name='الصف الدراسي'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الموظف')),
                ('national_id', models.CharField(blank=True, max_length=30, verbose_name='رقم الهوية')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('specialization', models.CharField(max_length=120, verbose_name='التخصص')),
                ('qualification', models.CharField(blank=True, max_length=150, verbose_name='المؤهل')),
                ('hire_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ التعيين')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الراتب الأساسي')),
                ('status', models.CharField(choices=[('active', 'على رأس العمل'), ('leave', 'إجازة'), ('inactive', 'غير نشط')], default='active', max_length=10, verbose_name='الحالة الوظيفية')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos/', verbose_name='الصورة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'أستاذ',
                'verbose_name_plural': 'الأساتذة',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='myapp.teacher', verbose_name='مربي الصف'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='myapp.teacher', verbose_name='المعلم'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'مالك النظام'), ('school_admin', 'مدير مدرسة'), ('accountant', 'محاسب'), ('teacher', 'معلم'), ('guardian', 'ولي أمر'), ('student', 'طالب')], max_length=20, verbose_name='الصلاحية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='myapp.guardian', verbose_name='ولي الأمر المرتبط')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.school', verbose_name='المدرسة')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='myapp.student', verbose_name='الطالب المرتبط')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='myapp.teacher', verbose_name='المعلم المرتبط')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف مستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('late', 'متأخر'), ('excused', 'بعذر'), ('absent', 'غائب')], max_length=10, verbose_name='الحالة')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='myapp.course', verbose_name='المادة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='myapp.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'unique_together': {('student', 'course', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='الدرجة')),
                ('feedback', models.TextField(blank=True, verbose_name='ملاحظات المعلم')),
                ('graded_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الرصد')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='myapp.assessment', verbose_name='الاختبار')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='myapp.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'درجة',
                'verbose_name_plural': 'الدرجات',
                'unique_together': {('student', 'assessment')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('school', 'academic_year', 'name')},
        ),
    ]
