# Generated by Django 5.2.16 on 2026-07-12 17:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_academicyear_feecategory_guardian_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='school',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='school',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='school',
        ),
        migrations.RemoveField(
            model_name='course',
            name='school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.RemoveField(
            model_name='feecategory',
            name='school',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='school',
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-due_date', 'course__name'], 'verbose_name': 'تقييم', 'verbose_name_plural': 'التقييمات'},
        ),
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date', 'student__name'], 'verbose_name': 'سجل حضور', 'verbose_name_plural': 'سجلات الحضور'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['level', 'name'], 'verbose_name': 'مادة', 'verbose_name_plural': 'المواد'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrollment_date'], 'verbose_name': 'تسجيل', 'verbose_name_plural': 'التسجيلات'},
        ),
        migrations.AlterModelOptions(
            name='feecategory',
            options={'ordering': ['name'], 'verbose_name': 'بند مالي', 'verbose_name_plural': 'البنود المالية'},
        ),
        migrations.AlterModelOptions(
            name='graderecord',
            options={'ordering': ['-graded_at'], 'verbose_name': 'رصد درجة', 'verbose_name_plural': 'رصد الدرجات'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['due_date', '-created_at'], 'verbose_name': 'فاتورة', 'verbose_name_plural': 'الفواتير'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-id'], 'verbose_name': 'دفعة', 'verbose_name_plural': 'الدفعات'},
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['academic_year__start_date', 'level', 'section', 'name'], 'verbose_name': 'صف دراسي', 'verbose_name_plural': 'الصفوف الدراسية'},
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='national_id',
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('academic_year', 'name')},
        ),
        migrations.RemoveField(
            model_name='student',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='assessment',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='تعليمات'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الوزن النسبي %'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='اسم جهة الطوارئ'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='هاتف الطوارئ'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='العام الدراسي'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('quiz', 'اختبار قصير'), ('exam', 'اختبار'), ('assignment', 'واجب'), ('project', 'مشروع'), ('participation', 'مشاركة')], max_length=20, verbose_name='نوع التقييم'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateField(verbose_name='تاريخ التقييم'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الدرجة العظمى'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='title',
            field=models.CharField(max_length=120, verbose_name='اسم التقييم'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='رمز المادة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.IntegerField(default=1, verbose_name='عدد الحصص/الساعات'),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='الدرجة النهائية'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='myapp.teacher', verbose_name='الأستاذ المسؤول'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الحضور'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الدرجة النهائية'),
        ),
        migrations.AlterField(
            model_name='feecategory',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='اسم البند المالي'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='myapp.assessment', verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='ملاحظات الأستاذ'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الدرجة المحققة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الخصم'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('pending', 'مستحقة'), ('partial', 'مدفوعة جزئيًا'), ('paid', 'مدفوعة'), ('overdue', 'متأخرة')], default='pending', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='myapp.teacher', verbose_name='المربي/المرشدة'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='level',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='الصف'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='القاعة'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير'), ('accountant', 'محاسب'), ('teacher', 'معلم'), ('guardian', 'ولي أمر')], max_length=15, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='myapp.teacher', verbose_name='الأستاذ المرتبط'),
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='school',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
