# Generated by Django 5.2.16 on 2026-07-12 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_invoice_school_remove_teacher_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='المحافظة')),
                ('city', models.CharField(max_length=100, verbose_name='المديرية')),
                ('state', models.CharField(max_length=100, verbose_name='العزلة')),
                ('country', models.CharField(max_length=100, verbose_name='القرية')),
            ],
            options={
                'verbose_name': 'العنوان',
                'verbose_name_plural': 'العناوين',
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('second_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الأب')),
                ('third_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الثالث')),
                ('forth_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الرابع')),
                ('last_name', models.CharField(max_length=100, verbose_name='اسم العائلة')),
                ('zk_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='رقم البصمة')),
                ('marital_status', models.CharField(choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج')], default='أعزب', max_length=10, verbose_name='الحالة الاجتماعية')),
            ],
            options={
                'verbose_name': 'الاسم الكامل',
                'verbose_name_plural': 'الأسماء الكاملة',
            },
        ),
        migrations.CreateModel(
            name='PersonalIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, verbose_name='رقم البطاقة')),
                ('issue_date', models.DateField(verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('governorate', models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظة')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='المديرية')),
                ('sub_district', models.CharField(blank=True, max_length=50, null=True, verbose_name='العزلة')),
                ('village', models.CharField(blank=True, max_length=50, null=True, verbose_name='القرية')),
                ('blood_Type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True, verbose_name='فصيلة الدم')),
            ],
            options={
                'verbose_name': 'بطاقة الهوية الشخصية',
                'verbose_name_plural': 'بطاقات الهوية الشخصية',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني')),
                ('typestatus', models.CharField(choices=[('متوقف', 'متوقف'), ('ليس متوقف', 'ليس متوقف')], default='ليس متوقف', max_length=20, verbose_name='التوقف ')),
                ('stop_reason', models.TextField(blank=True, null=True, verbose_name='سبب التوقف')),
                ('academic_qualification', models.CharField(blank=True, choices=[('بدون مؤهل', 'بدون مؤهل'), ('ثانوي', 'ثانوي'), ('دبلوم مهني', 'دبلوم مهني'), ('دبلوم جامعي', 'دبلوم جامعي'), ('بكالوريوس', 'بكالوريوس'), ('دبلوم عالي', 'دبلوم عالي'), ('ماجستير', 'ماجستير'), ('دكتوراه', 'دكتوراه'), ('أستاذ دكتور', 'أستاذ دكتور')], max_length=50, null=True, verbose_name='المؤهل العلمي')),
                ('high_school_grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='معدل الثانوية العامة')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدخول')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الخروج')),
                ('status', models.CharField(blank=True, choices=[('جيد', 'جيد'), ('متوسط', 'متوسط'), ('ضعيف', 'ضعيف'), ('فقير جدًا', 'فقير جدًا'), ('يتيم', 'يتيم')], max_length=100, null=True, verbose_name='الحالة المادية')),
                ('male_children', models.PositiveIntegerField(blank=True, default='لايوجد', null=True, verbose_name='عدد الأولاد الذكور')),
                ('female_children', models.PositiveIntegerField(blank=True, default='لايوجد', null=True, verbose_name='عدد الأولاد الإناث')),
                ('total_children', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='إجمالي الأولاد')),
                ('marital_status', models.CharField(blank=True, choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج')], max_length=50, null=True, verbose_name='الحالة الاجتماعية')),
                ('health_condition', models.CharField(blank=True, choices=[('جيد', 'جيد'), ('متوسط', 'متوسط'), ('سيئ', 'سيئ'), ('ذو إعاقة', 'ذو إعاقة'), ('مريض مزمن', 'مريض مزمن')], max_length=255, null=True, verbose_name='الحالة الصحية')),
                ('is_present', models.BooleanField(default=True, verbose_name='متواجد')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.address', verbose_name='العنوان')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.name', verbose_name='الاسم')),
                ('national_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='myapp.personalidcard', verbose_name='البطاقة الشخصية')),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'الأشخاص',
            },
        ),
    ]
