# Generated by Django 5.2.16 on 2026-07-12 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_address_name_personalidcard_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='name',
            name='zk_id',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.person', verbose_name='الشخص'),
        ),
    ]
