# Generated by Django 5.2.16 on 2026-07-12 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_name_marital_status_remove_name_zk_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.person', verbose_name='الشخص'),
        ),
    ]
