# Generated by Django 5.2.16 on 2026-07-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_student_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'اسم', 'verbose_name_plural': 'الاسماء'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='academic_qualification',
        ),
        migrations.RemoveField(
            model_name='person',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='exit_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='high_school_grade',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='person',
            name='stop_reason',
        ),
        migrations.RemoveField(
            model_name='person',
            name='typestatus',
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='person',
            name='female_children',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='عدد الأولاد الإناث'),
        ),
        migrations.AlterField(
            model_name='person',
            name='male_children',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='عدد الأولاد الذكور'),
        ),
    ]
