# Generated by Django 5.2.16 on 2026-07-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_person_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], default=1, max_length=1, verbose_name='الجنس'),
            preserve_default=False,
        ),
    ]
