# Generated by Django 5.2.16 on 2026-07-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_academicyear_hijri_year_alter_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='hijri_year',
            field=models.PositiveIntegerField(blank=True, choices=[(1435, '1435 هـ'), (1436, '1436 هـ'), (1437, '1437 هـ'), (1438, '1438 هـ'), (1439, '1439 هـ'), (1440, '1440 هـ'), (1441, '1441 هـ'), (1442, '1442 هـ'), (1443, '1443 هـ'), (1444, '1444 هـ'), (1445, '1445 هـ'), (1446, '1446 هـ'), (1447, '1447 هـ'), (1448, '1448 هـ'), (1449, '1449 هـ'), (1450, '1450 هـ'), (1451, '1451 هـ'), (1452, '1452 هـ'), (1453, '1453 هـ'), (1454, '1454 هـ'), (1455, '1455 هـ'), (1456, '1456 هـ'), (1457, '1457 هـ'), (1458, '1458 هـ'), (1459, '1459 هـ'), (1460, '1460 هـ'), (1461, '1461 هـ'), (1462, '1462 هـ'), (1463, '1463 هـ'), (1464, '1464 هـ'), (1465, '1465 هـ')], null=True, verbose_name='السنة الهجرية'),
        ),
    ]
