# Generated by Django 5.2.16 on 2026-07-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_student_hijri_year_student_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_class',
        ),
    ]
