# Generated by Django 5.2.16 on 2026-07-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_course_school_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='specialization',
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='سنوات الخبرة'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=150, verbose_name='اسم الأستاذ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, choices=[('ثانوي', 'ثانوي'), ('دبلوم', 'دبلوم'), ('بكالوريوس', 'بكالوريوس'), ('ماجستير', 'ماجستير'), ('دكتوراه', 'دكتوراه'), ('أخرى', 'أخرى')], max_length=20, verbose_name='المؤهل'),
        ),
    ]
