# Generated by Django 5.2.16 on 2026-07-13 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_teacher_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='employee_id',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='سنين الخبرة'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.person', verbose_name='الشخص'),
        ),
    ]
