# Generated by Django 5.2.16 on 2026-07-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_teacher_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_type',
            field=models.CharField(choices=[('fixed', 'ثابت'), ('volunteer', 'متطوع'), ('contract', 'متعاقد'), ('temporary', 'مؤقت'), ('part_time', 'دوام جزئي'), ('substitute', 'بديل'), ('trainee', 'متدرب')], default='fixed', max_length=20, verbose_name='نوع المعلم'),
        ),
    ]
