# Generated by Django 5.2.16 on 2026-07-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_teacher_teacher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(blank=True, max_length=120, verbose_name='التخصص'),
        ),
    ]
